name: myapp
description: "A Saffron Supply Chain Management System."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.7.7
  cloud_functions: ^4.6.9
  firebase_messaging: ^14.7.19

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^13.2.0

  # UI & Utils
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.0
  image_picker: ^1.2.0
  
  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.11.1
  
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
